name: release

on:
  push:
    tags:
      - v2.*.*
    branches-ignore:
      - '**'

jobs:
  make-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: bash ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: caddy-custom_linux_amd64.tar.gz